### ISSUE TITLE
can we like get access of what the child does in the apps mainly social media apps? is it possible using allows

### ISSUE THREAD

**Issue by abdulahadfolio** [Allow2/Allow2iOS#7]

**Comment by Allow2CEO** [comment]
No.

Allow2 is not involved in any privacy-related activity. We make a conscious effort to focus solely on assisting parents to both teach responsible screen time usage. This is purely to assist in helping focus and developing a more rounded approach to technology utilization beside personal interaction and sports/outdoor activity.

As such we do not share more than very top level usage type information (hours of gaming, social media, internet, etc).
We do not go into tracking locations, spying on texts and phone calls, etc etc.

Having said that, if you have a specific use case, please let us know via uses@allow2.com and we can evaluate if it makes sense to add a counter or timer activity for everyone.

Thanks for your interest in Allow2!
